[build]
  # 빌드 명령을 실행할 'base' 디렉토리를 지정합니다. (이전 빌드 로그에서 확인된 위치)
  # React 코드가 'frontend' 안에 있으므로, 빌드는 여기서 시작해야 합니다.

  
  # 'frontend' 폴더 안에서 React 빌드 명령을 실행합니다. (현재 명령어)
  command = "npm run build"
  
  # 빌드 결과물이 배포될 폴더입니다. (frontend/build가 됨)
  publish = "build"
  
  # Functions 코드가 있는 폴더를 지정합니다. 
  # 'base = "frontend"' 설정 시, Functions 경로는 이 'base'를 기준으로 계산됩니다.
  # 우리의 Functions 폴더는 루트에 있으므로, 상위 폴더를 참조해야 합니다.
  functions = "../netlify/functions" 


# API 요청을 Netlify Functions로 라우팅하는 Redirects 규칙 (ELK 연동)
[[redirects]]
  from = "/api/*"
  # to 경로에 있는 /.netlify/functions는 고정된 경로입니다.
  to = "/.netlify/functions/:splat"
  status = 200